### PR TITLE
Make issues link relative

### PR DESCRIPTION
**Pull request by aranasaurus**

### CODE REVIEW

**Comment by aranasaurus** [comment]
:bird: :bikini:

**Comment by ungoldman** [comment]
@aranasaurus++. The `../../` is weird but after doing some homework it seems like that is the only smart way to do that. You might also want to do the same for the other link.

**Comment by ungoldman** [comment]
aaaand you beat me to it within seconds

**Comment by ungoldman** [comment]
also if you want to fork this and use it as your own it should probably be from @maxogden, he did it first.

:bow: 

http://github.com/maxogden/messages

**Comment by aranasaurus** [comment]
I fork who I wanna fork, pal.

**Comment by ungoldman** [comment]
:fork_and_knife:

**Pull request merged**
